// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Af2-7I77719iuoPFLyvndVxuakTpriw',
    appId: '1:405197341911:web:88077f23efab6e29305c92',
    messagingSenderId: '405197341911',
    projectId: 'accounts-software-4a8a0',
    authDomain: 'accounts-software-4a8a0.firebaseapp.com',
    storageBucket: 'accounts-software-4a8a0.firebasestorage.app',
    measurementId: 'G-50X2D2HJ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeuNngo4cN7b4KIqdx5_9Wu1xVVaL6Zx8',
    appId: '1:77911016174:android:4443cc5b63be002a0229ff',
    messagingSenderId: '77911016174',
    projectId: 'daily-sales-app-23581',
    storageBucket: 'daily-sales-app-23581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhjKv7-sbSRy1eKttmRcD5ZcBNmhNjIDA',
    appId: '1:405197341911:ios:0ce0d62136778f58305c92',
    messagingSenderId: '405197341911',
    projectId: 'accounts-software-4a8a0',
    storageBucket: 'accounts-software-4a8a0.firebasestorage.app',
    iosBundleId: 'com.example.dailySales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhjKv7-sbSRy1eKttmRcD5ZcBNmhNjIDA',
    appId: '1:405197341911:ios:0ce0d62136778f58305c92',
    messagingSenderId: '405197341911',
    projectId: 'accounts-software-4a8a0',
    storageBucket: 'accounts-software-4a8a0.firebasestorage.app',
    iosBundleId: 'com.example.dailySales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Af2-7I77719iuoPFLyvndVxuakTpriw',
    appId: '1:405197341911:web:7a5f4e4cec2b5a12305c92',
    messagingSenderId: '405197341911',
    projectId: 'accounts-software-4a8a0',
    authDomain: 'accounts-software-4a8a0.firebaseapp.com',
    storageBucket: 'accounts-software-4a8a0.firebasestorage.app',
    measurementId: 'G-PT4MKW0JX3',
  );
}